[package]
name = "spela_klart"
version = "0.1.0"
authors = ["Johan Ã–hlin <johanohlin@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpd = "*"
